import { SvgFromXml } from "react-native-svg";
import icons from "./flags"


const country = {
    af: {
        countryCode: "AFG",
        phoneCode: "93",
        countryName: "Afghanistan",
        image: icons.af.imagexml,
        numberDigit: 9,
    },
    al: {
        countryCode: "ALB",
        phoneCode: "355",
        countryName: "Albania",
        image: icons.al.imagexml,
        numberDigit: 8,
    },
    dz: {
        countryCode: "DZA",
        phoneCode: "213",
        countryName: "Algeria",
        image: icons.dz.imagexml,
        numberDigit: 9,
    },
    as: {
        countryCode: "ASM",
        phoneCode: "1",
        countryName: "American Samoa",
        image: icons.as.imagexml,
        numberDigit: 10,
    },
    ag: {
        countryCode: "AGO",
        phoneCode: "244",
        countryName: "Angola",
        image: icons.ag.imagexml,
        numberDigit: 9,
    },
    ai: {
        countryCode: "AIA",
        phoneCode: "1",
        countryName: "Anguilla",
        image: icons.ai.imagexml,
        numberDigit: 10,
    },
    at: {
        countryCode: "ATA",
        phoneCode: "672",
        countryName: "Antarctica",
        image: icons.at.imagexml,
        numberDigit: 9,
    },
    ar: {
        countryCode: "ARG",
        phoneCode: "54",
        countryName: "Argentina",
        image: icons.ar.imagexml,
        numberDigit: 10,
    },
    am: {
        countryCode: "ARM",
        phoneCode: "374",
        countryName: "Armenia",
        image: icons.am.imagexml,
        numberDigit: 8,
    },
    au: {
        countryCode: "AUS",
        phoneCode: "61",
        countryName: "Australia",
        image: icons.au.imagexml,
        numberDigit: 9,
    },
    at: {
        countryCode: "AUT",
        phoneCode: "43",
        countryName: "Austria",
        image: icons.at.imagexml,
        numberDigit: 9,
    },
    az: {
        countryCode: "AZE",
        phoneCode: "994",
        countryName: "Azerbaijan",
        image: icons.az.imagexml,
        numberDigit: 9,
    },
    bg: {
        countryCode: "BHS",
        phoneCode: "1",
        countryName: "Bahamas",
        image: icons.bg.imagexml,
        numberDigit: 10,
    },
    bh: {
        countryCode: "BHR",
        phoneCode: "973",
        countryName: "Bahrain",
        image: icons.bh.imagexml,
        numberDigit: 8,
    },
    bd: {
        countryCode: "BGD",
        phoneCode: "880",
        countryName: "Bangladesh",
        image: icons.bd.imagexml,
        numberDigit: 9,
    },
    bb: {
        countryCode: "BRB",
        phoneCode: "1",
        countryName: "Barbados",
        image: icons.bb.imagexml,
        numberDigit: 10,
    },
    bg: {
        countryCode: "BLR",
        phoneCode: "375",
        countryName: "Belarus",
        image: icons.bg.imagexml,
        numberDigit: 9,
    },
    be: {
        countryCode: "BEL",
        phoneCode: "32",
        countryName: "Belgium",
        image: icons.be.imagexml,
        numberDigit: 9,
    },
    bz: {
        countryCode: "BLZ",
        phoneCode: "501",
        countryName: "Belize",
        image: icons.bz.imagexml,
        numberDigit: 7,
    },
    bj: {
        countryCode: "BEN",
        phoneCode: "229",
        countryName: "Benin",
        image: icons.bj.imagexml,
        numberDigit: 8,
    },
    bm: {
        countryCode: "BMU",
        phoneCode: "1",
        countryName: "Bermuda",
        image: icons.bm.imagexml,
        numberDigit: 10,
    },
    bt: {
        countryCode: "BTN",
        phoneCode: "975",
        countryName: "Bhutan",
        image: icons.bt.imagexml,
        numberDigit: 8,
    },
    bo: {
        countryCode: "BOL",
        phoneCode: "591",
        countryName: "Bolivia",
        image: icons.bo.imagexml,
        numberDigit: 8,
    },
    ba: {
        countryCode: "BIH",
        phoneCode: "387",
        countryName: "Bosnia & Herzegovina",
        image: icons.ba.imagexml,
        numberDigit: 8,
    },
    bw: {
        countryCode: "BWA",
        phoneCode: "267",
        countryName: "Botswana",
        image: icons.bw.imagexml,
        numberDigit: 8,
    },
    br: {
        countryCode: "BRA",
        phoneCode: "55",
        countryName: "Brazil",
        image: icons.br.imagexml,
        numberDigit: 10,
    },
    io: {
        countryCode: "IOT",
        phoneCode: "246",
        countryName: "British Indian Ocean Territory",
        image: icons.io.imagexml,
        numberDigit: 9,
    },
    vg: {
        countryCode: "VGB",
        phoneCode: "1",
        countryName: "British Virgin Islands",
        image: icons.vg.imagexml,
        numberDigit: 10,
    },
    bn: {
        countryCode: "BRN",
        phoneCode: "673",
        countryName: "Brunei",
        image: icons.bn.imagexml,
        numberDigit: 8,
    },
    bg: {
        countryCode: "BGR",
        phoneCode: "359",
        countryName: "Bulgaria",
        image: icons.bg.imagexml,
        numberDigit: 8,
    },
    bf: {
        countryCode: "BFA",
        phoneCode: "226",
        countryName: "Burkina Faso",
        image: icons.bf.imagexml,
        numberDigit: 8,
    },
    bi: {
        countryCode: "BDI",
        phoneCode: "257",
        countryName: "Burundi",
        image: icons.bi.imagexml,
        numberDigit: 8,
    },
    kh: {
        countryCode: "KHM",
        phoneCode: "855",
        countryName: "Cambodia",
        image: icons.kh.imagexml,
        numberDigit: 8,
    },
    cm: {
        countryCode: "CMR",
        phoneCode: "237",
        countryName: "Cameroon",
        image: icons.cm.imagexml,
        numberDigit: 8,
    },
    ca: {
        countryCode: "CAN",
        phoneCode: "1",
        countryName: "Canada",
        image: icons.ca.imagexml,
        numberDigit: 10,
    },
    cv: {
        countryCode: "CPV",
        phoneCode: "238",
        countryName: "Cape Verde",
        image: icons.cv.imagexml,
        numberDigit: 7,
    },
    ky: {
        countryCode: "CYM",
        phoneCode: "1",
        countryName: "Cayman Islands",
        image: icons.cy.imagexml,
        numberDigit: 10,
    },
    cf: {
        countryCode: "CAF",
        phoneCode: "236",
        countryName: "Central African Republic",
        image: icons.cf.imagexml,
        numberDigit: 8,
    },
    td: {
        countryCode: "TCD",
        phoneCode: "235",
        countryName: "Chad",
        image: icons.td.imagexml,
        numberDigit: 8,
    },
    cl: {
        countryCode: "CHL",
        phoneCode: "56",
        countryName: "Chile",
        image: icons.cl.imagexml,
        numberDigit: 8,
    },
    cn: {
        countryCode: "CHN",
        phoneCode: "86",
        countryName: "China",
        image: icons.cn.imagexml,
        numberDigit: 11,
    },
    cx: {
        countryCode: "CXR",
        phoneCode: "61",
        countryName: "Christmas Island",
        image: icons.cx.imagexml,
        numberDigit: 9,
    },
    cc: {
        countryCode: "CCK",
        phoneCode: "61",
        countryName: "Cocos Islands",
        image: icons.cc.imagexml,
        numberDigit: 9,
    },
    co: {
        countryCode: "COL",
        phoneCode: "57",
        countryName: "Colombia",
        image: icons.co.imagexml,
        numberDigit: 10,
    },
    km: {
        countryCode: "COM",
        phoneCode: "269",
        countryName: "Comoros",
        image: icons.km.imagexml,
        numberDigit: 8,
    },
    ck: {
        countryCode: "COK",
        phoneCode: "682",
        countryName: "Cook Islands",
        image: icons.ck.imagexml,
        numberDigit: 5,
    },
    cr: {
        countryCode: "CRI",
        phoneCode: "506",
        countryName: "Costa Rica",
        image: icons.cr.imagexml,
        numberDigit: 8,
    },
    hr: {
        countryCode: "HRV",
        phoneCode: "385",
        countryName: "Croatia",
        image: icons.hr.imagexml,
        numberDigit: 9,
    },
    cu: {
        countryCode: "CUB",
        phoneCode: "53",
        countryName: "Cuba",
        image: icons.cu.imagexml,
        numberDigit: 8,
    },
    cw: {
        countryCode: "CUW",
        phoneCode: "599",
        countryName: "Curaçao",
        image: icons.cw.imagexml,
        numberDigit: 7,
    },
    cy: {
        countryCode: "CYP",
        phoneCode: "357",
        countryName: "Cyprus",
        image: icons.cy.imagexml,
        numberDigit: 8,
    },
    cz: {
        countryCode: "CZE",
        phoneCode: "420",
        countryName: "Czech Republic",
        image: icons.cz.imagexml,
        numberDigit: 9,
    },
    cd: {
        countryCode: "COD",
        phoneCode: "243",
        countryName: "Democratic Republic of the Congo",
        image: icons.cd.imagexml,
        numberDigit: 9,
    },
    dk: {
        countryCode: "DNK",
        phoneCode: "45",
        countryName: "Denmark",
        image: icons.dk.imagexml,
        numberDigit: 8,
    },
    dj: {
        countryCode: "DJI",
        phoneCode: "253",
        countryName: "Djibouti",
        image: icons.dj.imagexml,
        numberDigit: 8,
    },
    dm: {
        countryCode: "DMA",
        phoneCode: "1",
        countryName: "Dominica",
        image: icons.dm.imagexml,
        numberDigit: 10,
    },
    do: {
        countryCode: "DOM",
        phoneCode: "1",
        countryName: "Dominican Republic",
        image: icons.dk.imagexml,
        numberDigit: 10,
    },
    tl: {
        countryCode: "TLS",
        phoneCode: "670",
        countryName: "East Timor",
        image: icons.tl.imagexml,
        numberDigit: 8,
    },
    ec: {
        countryCode: "ECU",
        phoneCode: "593",
        countryName: "Ecuador",
        image: icons.ec.imagexml,
        numberDigit: 9,
    },
    eg: {
        countryCode: "EGY",
        phoneCode: "20",
        countryName: "Egypt",
        image: icons.eg.imagexml,
        numberDigit: 8,
    },
    sv: {
        countryCode: "SLV",
        phoneCode: "503",
        countryName: "El Salvador",
        image: icons.sv.imagexml,
        numberDigit: 8,
    },
    gq: {
        countryCode: "GNQ",
        phoneCode: "240",
        countryName: "Equatorial Guinea",
        image: icons.gq.imagexml,
        numberDigit: 9,
    },
    er: {
        countryCode: "ERI",
        phoneCode: "291",
        countryName: "Eritrea",
        image: icons.er.imagexml,
        numberDigit: 8,
    },
    ee: {
        countryCode: "EST",
        phoneCode: "372",
        countryName: "Estonia",
        image: icons.ee.imagexml,
        numberDigit: 8,
    },
    et: {
        countryCode: "ETH",
        phoneCode: "251",
        countryName: "Ethiopia",
        image: icons.et.imagexml,
        numberDigit: 9,
    },
    fk: {
        countryCode: "FLK",
        phoneCode: "500",
        countryName: "Falkland Islands",
        image: icons.fk.imagexml,
        numberDigit: 5,
    },
    fo: {
        countryCode: "FRO",
        phoneCode: "298",
        countryName: "Faroe Islands",
        image: icons.fo.imagexml,
        numberDigit: 6,
    },
    fj: {
        countryCode: "FJI",
        phoneCode: "679",
        countryName: "Fiji",
        image: icons.fj.imagexml,
        numberDigit: 7,
    },
    fi: {
        countryCode: "FIN",
        phoneCode: "358",
        countryName: "Finland",
        image: icons.fi.imagexml,
        numberDigit: 10,
    },
    fr: {
        countryCode: "FRA",
        phoneCode: "33",
        countryName: "France",
        image: icons.fr.imagexml,
        numberDigit: 9,
    },
    gf: {
        countryCode: "GUF",
        phoneCode: "594",
        countryName: "French Guiana",
        image: icons.gf.imagexml,
        numberDigit: 9,
    },
    pf: {
        countryCode: "PYF",
        phoneCode: "689",
        countryName: "French Polynesia",
        image: icons.pf.imagexml,
        numberDigit: 8,
    },
    ga: {
        countryCode: "GAB",
        phoneCode: "241",
        countryName: "Gabon",
        image: icons.ga.imagexml,
        numberDigit: 7,
    },
    gm: {
        countryCode: "GMB",
        phoneCode: "220",
        countryName: "Gambia",
        image: icons.gm.imagexml,
        numberDigit: 7,
    },
    ge: {
        countryCode: "GEO",
        phoneCode: "995",
        countryName: "Georgia",
        image: icons.ge.imagexml,
        numberDigit: 9,
    },
    de: {
        countryCode: "DEU",
        phoneCode: "49",
        countryName: "Germany",
        image: icons.de.imagexml,
        numberDigit: 10,
    },
    gh: {
        countryCode: "GHA",
        phoneCode: "233",
        countryName: "Ghana",
        image: icons.gh.imagexml,
        numberDigit: 9,
    },
    gi: {
        countryCode: "GIB",
        phoneCode: "350",
        countryName: "Gibraltar",
        image: icons.gi.imagexml,
        numberDigit: 8,
    },
    gr: {
        countryCode: "GRC",
        phoneCode: "30",
        countryName: "Greece",
        image: icons.gr.imagexml,
        numberDigit: 10,
    },
    gl: {
        countryCode: "GRL",
        phoneCode: "299",
        countryName: "Greenland",
        image: icons.gl.imagexml,
        numberDigit: 6,
    },
    gd: {
        countryCode: "GRD",
        phoneCode: "1",
        countryName: "Grenada",
        image: icons.gd.imagexml,
        numberDigit: 10,
    },
    gp: {
        countryCode: "GLP",
        phoneCode: "590",
        countryName: "Guadeloupe",
        image: icons.gp.imagexml,
        numberDigit: 9,
    },
    gu: {
        countryCode: "GUM",
        phoneCode: "1",
        countryName: "Guam",
        image: icons.gu.imagexml,
        numberDigit: 10,
    },
    gt: {
        countryCode: "GTM",
        phoneCode: "502",
        countryName: "Guatemala",
        image: icons.gt.imagexml,
        numberDigit: 8,
    },
    gg: {
        countryCode: "GGY",
        phoneCode: "44",
        countryName: "Guernsey",
        image: icons.gg.imagexml,
        numberDigit: 10,
    },
    gn: {
        countryCode: "GIN",
        phoneCode: "224",
        countryName: "Guinea",
        image: icons.gn.imagexml,
        numberDigit: 8,
    },
    gw: {
        countryCode: "GNB",
        phoneCode: "245",
        countryName: "Guinea-Bissau",
        image: icons.gw.imagexml,
        numberDigit: 7,
    },
    gy: {
        countryCode: "GUY",
        phoneCode: "592",
        countryName: "Guyana",
        image: icons.gy.imagexml,
        numberDigit: 7,
    },
    ht: {
        countryCode: "HTI",
        phoneCode: "509",
        countryName: "Haiti",
        image: icons.ht.imagexml,
        numberDigit: 8,
    },
    hn: {
        countryCode: "HND",
        phoneCode: "504",
        countryName: "Honduras",
        image: icons.hn.imagexml,
        numberDigit: 8,
    },
    hk: {
        countryCode: "HKG",
        phoneCode: "852",
        countryName: "Hong Kong",
        image: icons.hk.imagexml,
        numberDigit: 8,
    },
    hu: {
        countryCode: "HUN",
        phoneCode: "36",
        countryName: "Hungary",
        image: icons.hu.imagexml,
        numberDigit: 9,
    },
    is: {
        countryCode: "ISL",
        phoneCode: "354",
        countryName: "Iceland",
        image: icons.is.imagexml,
        numberDigit: 7,
    },
    in: {
        countryCode: "IND",
        phoneCode: "91",
        countryName: "India",
        image: icons.in.imagexml,
        numberDigit: 10,
    },
    id: {
        countryCode: "IDN",
        phoneCode: "62",
        countryName: "Indonesia",
        image: icons.id.imagexml,
        numberDigit: 9,
    },
    ir: {
        countryCode: "IRN",
        phoneCode: "98",
        countryName: "Iran",
        image: icons.ir.imagexml,
        numberDigit: 10,
    },
    iq: {
        countryCode: "IRQ",
        phoneCode: "964",
        countryName: "Iraq",
        image: icons.iq.imagexml,
        numberDigit: 10,
    },
    ie: {
        countryCode: "IRL",
        phoneCode: "353",
        countryName: "Ireland",
        image: icons.ie.imagexml,
        numberDigit: 10,
    },
    im: {
        countryCode: "IMN",
        phoneCode: "44",
        countryName: "Isle of Man",
        image: icons.im.imagexml,
        numberDigit: 10,
    },
    il: {
        countryCode: "ISR",
        phoneCode: "972",
        countryName: "Israel",
        image: icons.il.imagexml,
        numberDigit: 9,
    },
    it: {
        countryCode: "ITA",
        phoneCode: "39",
        countryName: "Italy",
        image: icons.it.imagexml,
        numberDigit: 10,
    },
    ci: {
        countryCode: "CIV",
        phoneCode: "225",
        countryName: "Ivory Coast",
        image: icons.ci.imagexml,
        numberDigit: 8,
    },
    jm: {
        countryCode: "JAM",
        phoneCode: "1",
        countryName: "Jamaica",
        image: icons.jm.imagexml,
        numberDigit: 10,
    },
    jp: {
        countryCode: "JPN",
        phoneCode: "81",
        countryName: "Japan",
        image: icons.jp.imagexml,
        numberDigit: 10,
    },
    je: {
        countryCode: "JEY",
        phoneCode: "44",
        countryName: "Jersey",
        image: icons.je.imagexml,
        numberDigit: 10,
    },
    jo: {
        countryCode: "JOR",
        phoneCode: "962",
        countryName: "Jordan",
        image: icons.jo.imagexml,
        numberDigit: 8,
    },
    kz: {
        countryCode: "KAZ",
        phoneCode: "7",
        countryName: "Kazakhstan",
        image: icons.kz.imagexml,
        numberDigit: 10,
    },
    ke: {
        countryCode: "KEN",
        phoneCode: "254",
        countryName: "Kenya",
        image: icons.ke.imagexml,
        numberDigit: 9,
    },
    ki: {
        countryCode: "KIR",
        phoneCode: "686",
        countryName: "Kiribati",
        image: icons.ki.imagexml,
        numberDigit: 5,
    },
    xk: {
        countryCode: "XKX",
        phoneCode: "383",
        countryName: "Kosovo",
        image: icons.xk.imagexml,
        numberDigit: 8,
    },
    kw: {
        countryCode: "KWT",
        phoneCode: "965",
        countryName: "Kuwait",
        image: icons.kw.imagexml,
        numberDigit: 8,
    },
    kg: {
        countryCode: "KGZ",
        phoneCode: "996",
        countryName: "Kyrgyzstan",
        image: icons.kg.imagexml,
        numberDigit: 9,
    },
    la: {
        countryCode: "LAO",
        phoneCode: "856",
        countryName: "Laos",
        image: icons.la.imagexml,
        numberDigit: 8,
    },
    lv: {
        countryCode: "LVA",
        phoneCode: "371",
        countryName: "Latvia",
        image: icons.lv.imagexml,
        numberDigit: 8,
    },
    lb: {
        countryCode: "LBN",
        phoneCode: "961",
        countryName: "Lebanon",
        image: icons.lb.imagexml,
        numberDigit: 8,
    },
    ls: {
        countryCode: "LSO",
        phoneCode: "266",
        countryName: "Lesotho",
        image: icons.ls.imagexml,
        numberDigit: 8,
    },
    lr: {
        countryCode: "LBR",
        phoneCode: "231",
        countryName: "Liberia",
        image: icons.lr.imagexml,
        numberDigit: 7,
    },
    ly: {
        countryCode: "LBY",
        phoneCode: "218",
        countryName: "Libya",
        image: icons.ly.imagexml,
        numberDigit: 8,
    },
    li: {
        countryCode: "LIE",
        phoneCode: "423",
        countryName: "Liechtenstein",
        image: icons.li.imagexml,
        numberDigit: 7,
    },
    lt: {
        countryCode: "LTU",
        phoneCode: "370",
        countryName: "Lithuania",
        image: icons.lt.imagexml,
        numberDigit: 8,
    },
    lu: {
        countryCode: "LUX",
        phoneCode: "352",
        countryName: "Luxembourg",
        image: icons.lu.imagexml,
        numberDigit: 9,
    },
    mo: {
        countryCode: "MAC",
        phoneCode: "853",
        countryName: "Macao",
        image: icons.mo.imagexml,
        numberDigit: 8,
    },
    mk: {
        countryCode: "MKD",
        phoneCode: "389",
        countryName: "Macedonia",
        image: icons.mk.imagexml,
        numberDigit: 8,
    },
    mg: {
        countryCode: "MDG",
        phoneCode: "261",
        countryName: "Madagascar",
        image: icons.mg.imagexml,
        numberDigit: 9,
    },
    mw: {
        countryCode: "MWI",
        phoneCode: "265",
        countryName: "Malawi",
        image: icons.mw.imagexml,
        numberDigit: 8,
    },
    my: {
        countryCode: "MYS",
        phoneCode: "60",
        countryName: "Malaysia",
        image: icons.my.imagexml,
        numberDigit: 9,
    },
    mv: {
        countryCode: "MDV",
        phoneCode: "960",
        countryName: "Maldives",
        image: icons.mv.imagexml,
        numberDigit: 7,
    },
    ml: {
        countryCode: "MLI",
        phoneCode: "223",
        countryName: "Mali",
        image: icons.ml.imagexml,
        numberDigit: 8,
    },
    mt: {
        countryCode: "MLT",
        phoneCode: "356",
        countryName: "Malta",
        image: icons.mt.imagexml,
        numberDigit: 8,
    },
    mh: {
        countryCode: "MHL",
        phoneCode: "692",
        countryName: "Marshall Islands",
        image: icons.mh.imagexml,
        numberDigit: 7,
    },
    mq: {
        countryCode: "MTQ",
        phoneCode: "596",
        countryName: "Martinique",
        image: icons.mq.imagexml,
        numberDigit: 9,
    },
    mr: {
        countryCode: "MRT",
        phoneCode: "222",
        countryName: "Mauritania",
        image: icons.mr.imagexml,
        numberDigit: 8,
    },
    mu: {
        countryCode: "MUS",
        phoneCode: "230",
        countryName: "Mauritius",
        image: icons.mu.imagexml,
        numberDigit: 7,
    },
    mx: {
        countryCode: "MEX",
        phoneCode: "52",
        countryName: "Mexico",
        image: icons.mx.imagexml,
        numberDigit: 10,
    },
    fm: {
        countryCode: "FSM",
        phoneCode: "691",
        countryName: "Micronesia",
        image: icons.fm.imagexml,
        numberDigit: 7,
    },
    md: {
        countryCode: "MDA",
        phoneCode: "373",
        countryName: "Moldova",
        image: icons.md.imagexml,
        numberDigit: 8,
    },
    mc: {
        countryCode: "MCO",
        phoneCode: "377",
        countryName: "Monaco",
        image: icons.mc.imagexml,
        numberDigit: 8,
    },
    mn: {
        countryCode: "MNG",
        phoneCode: "976",
        countryName: "Mongolia",
        image: icons.mn.imagexml,
        numberDigit: 8,
    },
    me: {
        countryCode: "MNE",
        phoneCode: "382",
        countryName: "Montenegro",
        image: icons.me.imagexml,
        numberDigit: 8,
    },
    ma: {
        countryCode: "MAR",
        phoneCode: "212",
        countryName: "Morocco",
        image: icons.ma.imagexml,
        numberDigit: 9,
    },
    mz: {
        countryCode: "MOZ",
        phoneCode: "258",
        countryName: "Mozambique",
        image: icons.mz.imagexml,
        numberDigit: 8,
    },
    mm: {
        countryCode: "MMR",
        phoneCode: "95",
        countryName: "Myanmar",
        image: icons.mm.imagexml,
        numberDigit: 8,
    },
    na: {
        countryCode: "NAM",
        phoneCode: "264",
        countryName: "Namibia",
        image: icons.na.imagexml,
        numberDigit: 8,
    },
    nr: {
        countryCode: "NRU",
        phoneCode: "674",
        countryName: "Nauru",
        image: icons.nu.imagexml,
        numberDigit: 7,
    },
    np: {
        countryCode: "NPL",
        phoneCode: "977",
        countryName: "Nepal",
        image: icons.np.imagexml,
        numberDigit: 10,
    },
    nl: {
        countryCode: "NLD",
        phoneCode: "31",
        countryName: "Netherlands",
        image: icons.nl.imagexml,
        numberDigit: 9,
    },

    nc: {
        countryCode: "NCL",
        phoneCode: "687",
        countryName: "New Caledonia",
        image: icons.nc.imagexml,
        numberDigit: 6,
    },
    nz: {
        countryCode: "NZL",
        phoneCode: "64",
        countryName: "New Zealand",
        image: icons.nz.imagexml,
        numberDigit: 8,
    },
    ni: {
        countryCode: "NIC",
        phoneCode: "505",
        countryName: "Nicaragua",
        image: icons.ni.imagexml,
        numberDigit: 8,
    },
    ne: {
        countryCode: "NER",
        phoneCode: "227",
        countryName: "Niger",
        image: icons.ne.imagexml,
        numberDigit: 8,
    },
    ng: {
        countryCode: "NGA",
        phoneCode: "234",
        countryName: "Nigeria",
        image: icons.ng.imagexml,
        numberDigit: 10,
    },
    nu: {
        countryCode: "NIU",
        phoneCode: "683",
        countryName: "Niue",
        image: icons.nu.imagexml,
        numberDigit: 4,
    },
    nf: {
        countryCode: "NFK",
        phoneCode: "672",
        countryName: "Norfolk Island",
        image: icons.nf.imagexml,
        numberDigit: 8,
    },
    kp: {
        countryCode: "PRK",
        phoneCode: "850",
        countryName: "North Korea",
        image: icons.kp.imagexml,
        numberDigit: 9,
    },
    mp: {
        countryCode: "MNP",
        phoneCode: "1",
        countryName: "Northern Mariana Islands",
        image: icons.mp.imagexml,
        numberDigit: 10,
    },
    no: {
        countryCode: "NOR",
        phoneCode: "47",
        countryName: "Norway",
        image: icons.no.imagexml,
        numberDigit: 8,
    },
    om: {
        countryCode: "OMN",
        phoneCode: "968",
        countryName: "Oman",
        image: icons.om.imagexml,
        numberDigit: 8,
    },
    pk: {
        countryCode: "PAK",
        phoneCode: "92",
        countryName: "Pakistan",
        image: icons.pk.imagexml,
        numberDigit: 10,
    },
    pw: {
        countryCode: "PLW",
        phoneCode: "680",
        countryName: "Palau",
        image: icons.pw.imagexml,
        numberDigit: 7,
    },
    ps: {
        countryCode: "PSE",
        phoneCode: "970",
        countryName: "Palestine",
        image: icons.ps.imagexml,
        numberDigit: 8,
    },
    pa: {
        countryCode: "PAN",
        phoneCode: "507",
        countryName: "Panama",
        image: icons.pa.imagexml,
        numberDigit: 7,
    },
    pg: {
        countryCode: "PNG",
        phoneCode: "675",
        countryName: "Papua New Guinea",
        image: icons.pg.imagexml,
        numberDigit: 7,
    },
    py: {
        countryCode: "PRY",
        phoneCode: "595",
        countryName: "Paraguay",
        image: icons.py.imagexml,
        numberDigit: 9,
    },
    pe: {
        countryCode: "PER",
        phoneCode: "51",
        countryName: "Peru",
        image: icons.pe.imagexml,
        numberDigit: 9,
    },
    ph: {
        countryCode: "PHL",
        phoneCode: "63",
        countryName: "Philippines",
        image: icons.ph.imagexml,
        numberDigit: 10,
    },
    pn: {
        countryCode: "PCN",
        phoneCode: "870",
        countryName: "Pitcairn Islands",
        image: icons.pn.imagexml,
        numberDigit: 4,
    },
    pl: {
        countryCode: "POL",
        phoneCode: "48",
        countryName: "Poland",
        image: icons.pl.imagexml,
        numberDigit: 9,
    },
    pt: {
        countryCode: "PRT",
        phoneCode: "351",
        countryName: "Portugal",
        image: icons.pt.imagexml,
        numberDigit: 9,
    },
    pr: {
        countryCode: "PRI",
        phoneCode: "1",
        countryName: "Puerto Rico",
        image: icons.pr.imagexml,
        numberDigit: 10,
    },
    qa: {
        countryCode: "QAT",
        phoneCode: "974",
        countryName: "Qatar",
        image: icons.qa.imagexml,
        numberDigit: 8,
    },
    cg: {
        countryCode: "COG",
        phoneCode: "242",
        countryName: "Republic of the Congo",
        image: icons.cg.imagexml,
        numberDigit: 8,
    },
    re: {
        countryCode: "REU",
        phoneCode: "262",
        countryName: "Réunion",
        image: icons.re.imagexml,
        numberDigit: 9,
    },
    ro: {
        countryCode: "ROU",
        phoneCode: "40",
        countryName: "Romania",
        image: icons.ro.imagexml,
        numberDigit: 9,
    },
    ru: {
        countryCode: "RUS",
        phoneCode: "7",
        countryName: "Russia",
        image: icons.ru.imagexml,
        numberDigit: 10,
    },
    rw: {
        countryCode: "RWA",
        phoneCode: "250",
        countryName: "Rwanda",
        image: icons.rw.imagexml,
        numberDigit: 9,
    },
    bl: {
        countryCode: "BLM",
        phoneCode: "590",
        countryName: "Saint Barthélemy",
        image: icons.bl.imagexml,
        numberDigit: 9,
    },
    sh: {
        countryCode: "SHN",
        phoneCode: "290",
        countryName: "Saint Helena",
        image: icons.sh.imagexml,
        numberDigit: 4,
    },
    kn: {
        countryCode: "KNA",
        phoneCode: "1",
        countryName: "Saint Kitts and Nevis",
        image: icons.kn.imagexml,
        numberDigit: 10,
    },
    lc: {
        countryCode: "LCA",
        phoneCode: "1",
        countryName: "Saint Lucia",
        image: icons.lc.imagexml,
        numberDigit: 10,
    },
    mf: {
        countryCode: "MAF",
        phoneCode: "590",
        countryName: "Saint Martin",
        image: icons.mf.imagexml,
        numberDigit: 9,
    },
    pm: {
        countryCode: "SPM",
        phoneCode: "508",
        countryName: "Saint Pierre and Miquelon",
        image: icons.pm.imagexml,
        numberDigit: 6,
    },
    vc: {
        countryCode: "VCT",
        phoneCode: "1",
        countryName: "Saint Vincent and the Grenadines",
        image: icons.vc.imagexml,
        numberDigit: 10,
    },
    ws: {
        countryCode: "WSM",
        phoneCode: "685",
        countryName: "Samoa",
        image: icons.ws.imagexml,
        numberDigit: 7,
    },
    sm: {
        countryCode: "SMR",
        phoneCode: "378",
        countryName: "San Marino",
        image: icons.sm.imagexml,
        numberDigit: 8,
    },
    st: {
        countryCode: "STP",
        phoneCode: "239",
        countryName: "São Tomé and Príncipe",
        image: icons.st.imagexml,
        numberDigit: 7,
    },
    sa: {
        countryCode: "SAU",
        phoneCode: "966",
        countryName: "Saudi Arabia",
        image: icons.sa.imagexml,
        numberDigit: 9,
    },
    sn: {
        countryCode: "SEN",
        phoneCode: "221",
        countryName: "Senegal",
        image: icons.sn.imagexml,
        numberDigit: 9,
    },
    rs: {
        countryCode: "SRB",
        phoneCode: "381",
        countryName: "Serbia",
        image: icons.rs.imagexml,
        numberDigit: 8,
    },
    sc: {
        countryCode: "SYC",
        phoneCode: "248",
        countryName: "Seychelles",
        image: icons.sc.imagexml,
        numberDigit: 7,
    },
    sl: {
        countryCode: "SLE",
        phoneCode: "232",
        countryName: "Sierra Leone",
        image: icons.sl.imagexml,
        numberDigit: 8,
    },
    sg: {
        countryCode: "SGP",
        phoneCode: "65",
        countryName: "Singapore",
        image: icons.sg.imagexml,
        numberDigit: 8,
    },
    sx: {
        countryCode: "SXM",
        phoneCode: "1",
        countryName: "Sint Maarten",
        image: icons.sx.imagexml,
        numberDigit: 10,
    },
    sk: {
        countryCode: "SVK",
        phoneCode: "421",
        countryName: "Slovakia",
        image: icons.sk.imagexml,
        numberDigit: 9,
    },
    si: {
        countryCode: "SVN",
        phoneCode: "386",
        countryName: "Slovenia",
        image: icons.si.imagexml,
        numberDigit: 8,
    },
    sb: {
        countryCode: "SLB",
        phoneCode: "677",
        countryName: "Solomon Islands",
        image: icons.sb.imagexml,
        numberDigit: 7,
    },
    so: {
        countryCode: "SOM",
        phoneCode: "252",
        countryName: "Somalia",
        image: icons.so.imagexml,
        numberDigit: 8,
    },
    za: {
        countryCode: "ZAF",
        phoneCode: "27",
        countryName: "South Africa",
        image: icons.za.imagexml,
        numberDigit: 9,
    },
    kr: {
        countryCode: "KOR",
        phoneCode: "82",
        countryName: "South Korea",
        image: icons.kr.imagexml,
        numberDigit: 9,
    },
    ss: {
        countryCode: "SSD",
        phoneCode: "211",
        countryName: "South Sudan",
        image: icons.ss.imagexml,
        numberDigit: 9,
    },
    es: {
        countryCode: "ESP",
        phoneCode: "34",
        countryName: "Spain",
        image: icons.es.imagexml,
        numberDigit: 9,
    },
    lk: {
        countryCode: "LKA",
        phoneCode: "94",
        countryName: "Sri Lanka",
        image: icons.lk.imagexml,
        numberDigit: 9,
    },
    sd: {
        countryCode: "SDN",
        phoneCode: "249",
        countryName: "Sudan",
        image: icons.sd.imagexml,
        numberDigit: 9,
    },
    sr: {
        countryCode: "SUR",
        phoneCode: "597",
        countryName: "Suriname",
        image: icons.sr.imagexml,
        numberDigit: 7,
    },
    sj: {
        countryCode: "SJM",
        phoneCode: "47",
        countryName: "Svalbard and Jan Mayen",
        image: icons.sj.imagexml,
        numberDigit: 8,
    },
    sz: {
        countryCode: "SWZ",
        phoneCode: "268",
        countryName: "Swaziland",
        image: icons.sz.imagexml,
        numberDigit: 7,
    },
    se: {
        countryCode: "SWE",
        phoneCode: "46",
        countryName: "Sweden",
        image: icons.se.imagexml,
        numberDigit: 9,
    },
    ch: {
        countryCode: "CHE",
        phoneCode: "41",
        countryName: "Switzerland",
        image: icons.ch.imagexml,
        numberDigit: 9,
    },
    sy: {
        countryCode: "SYR",
        phoneCode: "963",
        countryName: "Syria",
        image: icons.sy.imagexml,
        numberDigit: 8,
    },
    tw: {
        countryCode: "TWN",
        phoneCode: "886",
        countryName: "Taiwan",
        image: icons.tw.imagexml,
        numberDigit: 8,
    },
    tj: {
        countryCode: "TJK",
        phoneCode: "992",
        countryName: "Tajikistan",
        image: icons.tj.imagexml,
        numberDigit: 9,
    },
    tz: {
        countryCode: "TZA",
        phoneCode: "255",
        countryName: "Tanzania",
        image: icons.tz.imagexml,
        numberDigit: 9,
    },
    th: {
        countryCode: "THA",
        phoneCode: "66",
        countryName: "Thailand",
        image: icons.th.imagexml,
        numberDigit: 9,
    },
    tl: {
        countryCode: "TLS",
        phoneCode: "670",
        countryName: "Timor-Leste",
        image: icons.tl.imagexml,
        numberDigit: 7,
    },
    tg: {
        countryCode: "TGO",
        phoneCode: "228",
        countryName: "Togo",
        image: icons.tg.imagexml,
        numberDigit: 8,
    },
    tk: {
        countryCode: "TKL",
        phoneCode: "690",
        countryName: "Tokelau",
        image: icons.tk.imagexml,
        numberDigit: 4,
    },
    to: {
        countryCode: "TON",
        phoneCode: "676",
        countryName: "Tonga",
        image: icons.to.imagexml,
        numberDigit: 5,
    },
    tt: {
        countryCode: "TTO",
        phoneCode: "1",
        countryName: "Trinidad and Tobago",
        image: icons.tt.imagexml,
        numberDigit: 10,
    },
    tn: {
        countryCode: "TUN",
        phoneCode: "216",
        countryName: "Tunisia",
        image: icons.tn.imagexml,
        numberDigit: 8,
    },
    tr: {
        countryCode: "TUR",
        phoneCode: "90",
        countryName: "Turkey",
        image: icons.tr.imagexml,
        numberDigit: 10,
    },
    tm: {
        countryCode: "TKM",
        phoneCode: "993",
        countryName: "Turkmenistan",
        image: icons.tm.imagexml,
        numberDigit: 8,
    },
    tc: {
        countryCode: "TCA",
        phoneCode: "1",
        countryName: "Turks and Caicos Islands",
        image: icons.tc.imagexml,
        numberDigit: 10,
    },
    tv: {
        countryCode: "TUV",
        phoneCode: "688",
        countryName: "Tuvalu",
        image: icons.tv.imagexml,
        numberDigit: 5,
    },
    ug: {
        countryCode: "UGA",
        phoneCode: "256",
        countryName: "Uganda",
        image: icons.ug.imagexml,
        numberDigit: 9,
    },
    ua: {
        countryCode: "UKR",
        phoneCode: "380",
        countryName: "Ukraine",
        image: icons.ua.imagexml,
        numberDigit: 9,
    },
    ae: {
        countryCode: "ARE",
        phoneCode: "971",
        countryName: "United Arab Emirates",
        image: icons.ae.imagexml,
        numberDigit: 9,
    },
    gb: {
        countryCode: "GBR",
        phoneCode: "44",
        countryName: "United Kingdom",
        image: icons.gb.imagexml,
        numberDigit: 10,
    },
    us: {
        countryCode: "USA",
        phoneCode: "1",
        countryName: "United States",
        image: icons.us.imagexml,
        numberDigit: 10,
    },
    uy: {
        countryCode: "URY",
        phoneCode: "598",
        countryName: "Uruguay",
        image: icons.uy.imagexml,
        numberDigit: 8,
    },
    uz: {
        countryCode: "UZB",
        phoneCode: "998",
        countryName: "Uzbekistan",
        image: icons.uz.imagexml,
        numberDigit: 9,
    },
    vu: {
        countryCode: "VUT",
        phoneCode: "678",
        countryName: "Vanuatu",
        image: icons.vu.imagexml,
        numberDigit: 6,
    },
    va: {
        countryCode: "VAT",
        phoneCode: "39",
        countryName: "Vatican City",
        image: icons.va.imagexml,
        numberDigit: 10,
    },
    ve: {
        countryCode: "VEN",
        phoneCode: "58",
        countryName: "Venezuela",
        image: icons.ve.imagexml,
        numberDigit: 10,
    },
    vn: {
        countryCode: "VNM",
        phoneCode: "84",
        countryName: "Vietnam",
        image: icons.vn.imagexml,
        numberDigit: 9,
    },
    vg: {
        countryCode: "VGB",
        phoneCode: "1",
        countryName: "British Virgin Islands",
        image: icons.vg.imagexml,
        numberDigit: 10,
    },
    vi: {
        countryCode: "VIR",
        phoneCode: "1",
        countryName: "U.S. Virgin Islands",
        image: icons.vi.imagexml,
        numberDigit: 10,
    },
    wf: {
        countryCode: "WLF",
        phoneCode: "681",
        countryName: "Wallis and Futuna",
        image: icons.wf.imagexml,
        numberDigit: 6,
    },
    eh: {
        countryCode: "ESH",
        phoneCode: "212",
        countryName: "Western Sahara",
        image: icons.ws.imagexml,
        numberDigit: 8,
    },
    ye: {
        countryCode: "YEM",
        phoneCode: "967",
        countryName: "Yemen",
        image: icons.ye.imagexml,
        numberDigit: 9,
    },
    zm: {
        countryCode: "ZMB",
        phoneCode: "260",
        countryName: "Zambia",
        image: icons.zm.imagexml,
        numberDigit: 9,
    },
    zw: {
        countryCode: "ZWE",
        phoneCode: "263",
        countryName: "Zimbabwe",
        image: icons.zw.imagexml,
        numberDigit: 9,
    },
};

const phoneCountry = getCountryWithPhoneCode()


function getCountryWithPhoneCode() {
    const phoneCountry = {}
    let keys = Object.keys(country)

    keys.forEach(item => {
        let key = country[item].phoneCode

        phoneCountry[key] = country[item]
    })

    return phoneCountry
}


function CountrySvgImage({ code, styles, width = 30, height = 30,  }) {
    
    let xml = country[code].image
    return (
        <SvgFromXml xml={xml} style={styles} width={width} height={height}  />
    )
}


export { phoneCountry, CountrySvgImage }
export default country



